### PR TITLE
Remove Foundation

### PR DESCRIPTION
**Pull request by deioo**
Remove Foundation as a vendor dependency and switch to Thoughtbot's Bourbon and Neat.

### CODE REVIEW

**Comment by Arkham** [comment]
I've seen that we use `global-transition-duration / 2` so maybe we want to use that as the default transition duration?

**Comment by Arkham** [comment]
:+1:

**Comment by Arkham** [comment]
This is amazing BTW :star2:

**Comment by deioo** [comment]
I'll update the settings to use maps and refactor all of these accordingly. We can do it in a separate PR

**Comment by carlosepp** [comment]
:trophy:

**Pull request merged**
