### PR TITLE
Implement a basic modal component

### PR DESCRIPTION
**Pull request by deioo**
The component includes:

* Responsive percentage width
* Automatic vertical centering
* Overflow scroll
* Animate in-out when .active class is added
* Close button
* Header / footer

The component uses the default overlay mixin for the background and the panel component for the container div.

The most basic markup

```html
<div class="modal">
  <div>
    <header>
      <h1>Modal Header</h1>

      <button class="close"></button>
    </header>

    <div class="content">
      Add content here.
    </div>
  </div>
</div>
```

### CODE REVIEW

**Comment by eugeniodepalo** [comment]
Great! Would it be possible to make the width dependent on the content? So that it's up to the user to use a grid row or not?

**Comment by deioo** [comment]
The grid-row doesnt add any kind of padding or spacing, it just resets the margins and adds a width: 100%.
So content that extends from left to right or columns can be added directly.

**Comment by eugeniodepalo** [comment]
But isn't there a fixed percentage width applied to the modal container?

**Comment by deioo** [comment]
The percentage is applied to a `.modal > div`, the `.content` inside just gets the 100% width of it's parent _(that's where the `%grid-row` extend`)_

**Comment by eugeniodepalo** [comment]
Yea, so this means that the modal width is independent of its content, right? My question is: can I create a modal where the width is dictated by the content and not by a percentage? (I might be misunderstanding the reason for the % width)

**Comment by Arkham** [comment]
:+1:

**Pull request merged**
