### PR TITLE
Sidebar Navigation Bubble

### PR DESCRIPTION
**Pull request by deioo**
This preview is a highlighted version, the standard bubble is grey and doesn't stand out that much.

screen shot 2015-05-18 at 11 05 49
---
screen shot 2015-05-18 at 11 06 06
---
Default preview:
screen shot 2015-05-18 at 11 18 05

### CODE REVIEW

**Comment by willrax** [comment]
I like the difference between the highlighted and non highlighted. We can make lemur highlight the number if it goes above a certain threshold.

**Comment by eugeniodepalo** [comment]
Nice! It might be the gif, but the number doesn't look centered in the first item of the list :P

**Comment by deioo** [comment]
it's the rem/px sub-pixel rendering bug.
The layout component is going to get refactored and I'll fix all these issues then.

**Comment by eugeniodepalo** [comment]
:+1:

**Pull request merged**
